apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-d-2329221
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-d-2329221
  template:
    metadata:
      labels:
        app: devops-d-2329221
    spec:
      containers:
        - name: devops-d-2329221
          image: devops-d-2329221:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80